// <auto-generated />
using System;
using LearnBlazor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnBlazor.Api.Migrations
{
    [DbContext(typeof(Task1DbContext))]
    [Migration("20240711102831_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnBlazor.Api.Entities.Task1", b =>
                {
                    b.Property<Guid?>("MHID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GIABANLE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MHCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MHTEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("MHID");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
